### ISSUE TITLE
Not calculating

### ISSUE THREAD

**Issue by sararigup** [igtm/storypoint-for-asana-chrome-ext#28]
It's just staying at 0 and I'm not sure it works for subtasks.

**Comment by igtm** [comment]
I'm not sure your detail situation.
Did you click the 'sync subtask' button for summing up subtasks?

![スクリーンショット 2020-06-02 14 34 00](https://user-images.githubusercontent.com/6331737/83483656-1e85c680-a4de-11ea-99c7-d7156c7cc09e.png)

**Comment by sararigup** [comment]
I figured it out! I thought it was using my custom field, I didn't see this
one yet but now it works. thank you!

*Sara Richardson*
sara.richardson@rigup.com | rigup.com

Connect with me on LinkedIn <https://www.linkedin.com/in/sara-richardson/>
