### ISSUE TITLE
Storypoints-selection is not shown anymore above the description field

### ISSUE THREAD

**Issue by andreasbossard** [igtm/storypoint-for-asana-chrome-ext#55]
![Bildschirmfoto 2022-08-17 um 08 33 13](https://user-images.githubusercontent.com/502464/185050788-a3e8c88a-873a-4c6a-a631-82c882177cbc.png)

**Comment by igtm** [comment]
Thank you for notifying!
I fixed this and uploaded new version just now, so you'll be able to use it soon!
