### ISSUE TITLE
Column totals are no longer adding up

### ISSUE THREAD

**Issue by hamcake** [igtm/storypoint-for-asana-chrome-ext#6]
Hi there - 
I noticed today that the column headers stopped being added up. They are just showing as 0. This is happening on a colleague's computer too. I've attached a screenshot.

![Screen Shot 2019-12-03 at 12 16 32 PM](https://user-images.githubusercontent.com/158139/70077663-e4874680-15c6-11ea-8032-e40394d363b8.png)

Thanks!

**Comment by igtm** [comment]
Closed by https://github.com/igtm/storypoint-for-asana-chrome-ext/pull/7
Thank you for reporting it :)
