### ISSUE TITLE
Remove point from title and use custom field

### ISSUE THREAD

**Issue by django23** [igtm/storypoint-for-asana-chrome-ext#9]
Hey hey,

Would it be possible to move the size of task out of the title but to a custom field like here:
![image](https://user-images.githubusercontent.com/827397/81667182-3e781c00-9443-11ea-8afd-7ffb7c741814.png)

Cheers,

**Comment by igtm** [comment]
Sorry, I dont't have a plan to add the function.
but You can get all your tasks with Asana's API.
See this link https://developers.asana.com/docs/get-multiple-tasks
